admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  clusters:
    name: cluster_0
    connect_timeout: 1s
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3306
  listeners:
    name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 9903
    filter_chains:
    - filters:
      - name: envoy.filters.network.mysql_proxy
        config:
          stat_prefix: mysql
      - name: envoy.tcp_proxy
        config:
          stat_prefix: tcp
          cluster: cluster_0
